//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MowerRainSteering.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string debug {
            get {
                return ((string)(this["debug"]));
            }
            set {
                this["debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int intervalToCheckRainSensor {
            get {
                return ((int)(this["intervalToCheckRainSensor"]));
            }
            set {
                this["intervalToCheckRainSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("martin@die-sickels.de")]
        public string emailForStatusMessages {
            get {
                return ((string)(this["emailForStatusMessages"]));
            }
            set {
                this["emailForStatusMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("martin@die-sickels.de")]
        public string emailForErrorMessages {
            get {
                return ((string)(this["emailForErrorMessages"]));
            }
            set {
                this["emailForErrorMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int startTimeForChecking {
            get {
                return ((int)(this["startTimeForChecking"]));
            }
            set {
                this["startTimeForChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int endTimeForChecking {
            get {
                return ((int)(this["endTimeForChecking"]));
            }
            set {
                this["endTimeForChecking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Olc9fYEGvzHHWUCJdo0LaBf8bj8ktuVo3DSVV56XHg4=")]
        public string netatmoClientId {
            get {
                return ((string)(this["netatmoClientId"]));
            }
            set {
                this["netatmoClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fh7bwq5npAe0NPMdsq6MSnzk7DZhHL1PZjX+nk0/sFJ52XdVuyAtMxE0G/MCK6rv")]
        public string netatmoClientSecret {
            get {
                return ((string)(this["netatmoClientSecret"]));
            }
            set {
                this["netatmoClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("netatmoUsernem")]
        public string netatmoLogin {
            get {
                return ((string)(this["netatmoLogin"]));
            }
            set {
                this["netatmoLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("netatmoPassword")]
        public string netatmoPassword {
            get {
                return ((string)(this["netatmoPassword"]));
            }
            set {
                this["netatmoPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gardenaUsername")]
        public string gardenaLogin {
            get {
                return ((string)(this["gardenaLogin"]));
            }
            set {
                this["gardenaLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gardenaPassword")]
        public string gardenaPassword {
            get {
                return ((string)(this["gardenaPassword"]));
            }
            set {
                this["gardenaPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("email who sends email")]
        public string emailFromEmail {
            get {
                return ((string)(this["emailFromEmail"]));
            }
            set {
                this["emailFromEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("username for your email account")]
        public string emailAccountUser {
            get {
                return ((string)(this["emailAccountUser"]));
            }
            set {
                this["emailAccountUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password for the email user account")]
        public string emailAccountUserPassword {
            get {
                return ((string)(this["emailAccountUserPassword"]));
            }
            set {
                this["emailAccountUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string emailSMTP {
            get {
                return ((string)(this["emailSMTP"]));
            }
            set {
                this["emailSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public string emailSMTPPort {
            get {
                return ((string)(this["emailSMTPPort"]));
            }
            set {
                this["emailSMTPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool emailSSL {
            get {
                return ((bool)(this["emailSSL"]));
            }
            set {
                this["emailSSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double rain {
            get {
                return ((double)(this["rain"]));
            }
            set {
                this["rain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sendEmailsStatus {
            get {
                return ((bool)(this["sendEmailsStatus"]));
            }
            set {
                this["sendEmailsStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sendEmailError {
            get {
                return ((bool)(this["sendEmailError"]));
            }
            set {
                this["sendEmailError"] = value;
            }
        }
    }
}
